/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bancojava;

/**
 *
 * @author Arthu
 */
public class MainFrame extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNewAccount = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        btnAccountData = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        newAccountMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameNewAccount = new javax.swing.JTextField();
        phoneNewAccount = new javax.swing.JTextField();
        moneyNewAccount = new javax.swing.JTextField();
        btnNewAccount2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        comboBoxAccountType = new javax.swing.JComboBox<>();
        btnBackFromNewAccountMenu = new javax.swing.JButton();
        withdrawMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        withdrawAccountNumber = new javax.swing.JTextField();
        btnWithdraw2 = new javax.swing.JButton();
        btnBackFromWithdrawMenu = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        withdrawAccountID = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        withdrawValue = new javax.swing.JTextField();
        withdrawMenu2 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        withdrawValue2 = new javax.swing.JLabel();
        btnCompleteWithdraw = new javax.swing.JButton();
        finalBalance = new javax.swing.JLabel();
        depositMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        depositValue = new javax.swing.JTextField();
        btnDeposit2 = new javax.swing.JButton();
        btnBackFromDepositMenu = new javax.swing.JButton();
        balanceMenu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        accountBalanceNumber = new javax.swing.JTextField();
        btnBalance2 = new javax.swing.JButton();
        accountBalanceId = new javax.swing.JComboBox<>();
        btnBackFromBalanceMenu = new javax.swing.JButton();
        balanceMenu2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnCompleteBalanceView = new javax.swing.JButton();
        accountBalance = new javax.swing.JLabel();
        accountDataMenu = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        accountDataNumber = new javax.swing.JTextField();
        btnSeeData = new javax.swing.JButton();
        accountDataId = new javax.swing.JComboBox<>();
        btnBackFromAccountDataMenu = new javax.swing.JButton();
        accountDataMenu2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        accountDataName = new javax.swing.JLabel();
        accountDataPhone = new javax.swing.JLabel();
        btnSeeAccountDataCompleted = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Banco Agiota");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Seu dinheiro, nossa vida!");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu inicial", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        btnNewAccount.setText("Criar conta");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });

        btnBalance.setText("Ver saldo");
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });

        btnAccountData.setText("Dados da conta");
        btnAccountData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccountDataActionPerformed(evt);
            }
        });

        btnWithdraw.setText("Sacar");
        btnWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdrawActionPerformed(evt);
            }
        });

        btnDeposit.setText("Depositar");
        btnDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAccountData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewAccount)
                    .addComponent(btnBalance)
                    .addComponent(btnAccountData))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw)
                    .addComponent(btnDeposit))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout startMenuLayout = new javax.swing.GroupLayout(startMenu);
        startMenu.setLayout(startMenuLayout);
        startMenuLayout.setHorizontalGroup(
            startMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startMenuLayout.createSequentialGroup()
                .addGroup(startMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(startMenuLayout.createSequentialGroup()
                        .addGroup(startMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(startMenuLayout.createSequentialGroup()
                                .addGap(154, 154, 154)
                                .addComponent(jLabel1))
                            .addGroup(startMenuLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        startMenuLayout.setVerticalGroup(
            startMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.getAccessibleContext().setAccessibleName("");

        jPanel1.add(startMenu, "card2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Hora de ter uma conta");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("com a gente!");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Valor inicial:");

        nameNewAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        phoneNewAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        moneyNewAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnNewAccount2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNewAccount2.setText("Criar conta");
        btnNewAccount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccount2ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Tipo de conta:");

        comboBoxAccountType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Corrente", "2- Poupança" }));

        btnBackFromNewAccountMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBackFromNewAccountMenu.setText("Voltar");
        btnBackFromNewAccountMenu.setPreferredSize(new java.awt.Dimension(115, 32));
        btnBackFromNewAccountMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFromNewAccountMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newAccountMenuLayout = new javax.swing.GroupLayout(newAccountMenu);
        newAccountMenu.setLayout(newAccountMenuLayout);
        newAccountMenuLayout.setHorizontalGroup(
            newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnNewAccount2)))
                .addGap(139, 139, 139))
            .addGroup(newAccountMenuLayout.createSequentialGroup()
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAccountMenuLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newAccountMenuLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moneyNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackFromNewAccountMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel3))
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(jLabel4)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        newAccountMenuLayout.setVerticalGroup(
            newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackFromNewAccountMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(phoneNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(comboBoxAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNewAccount2)
                .addGap(51, 51, 51))
        );

        jPanel1.add(newAccountMenu, "card3");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("Precisando de uma grana, né!");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Quanto você precisa?");

        withdrawAccountNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnWithdraw2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnWithdraw2.setText("Sacar");
        btnWithdraw2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithdraw2ActionPerformed(evt);
            }
        });

        btnBackFromWithdrawMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBackFromWithdrawMenu.setText("Voltar");
        btnBackFromWithdrawMenu.setPreferredSize(new java.awt.Dimension(115, 32));
        btnBackFromWithdrawMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFromWithdrawMenuActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("ID:");

        withdrawAccountID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        withdrawAccountID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Corrente", "2- Poupança" }));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("Conta:");

        withdrawValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        withdrawValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawValueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout withdrawMenuLayout = new javax.swing.GroupLayout(withdrawMenu);
        withdrawMenu.setLayout(withdrawMenuLayout);
        withdrawMenuLayout.setHorizontalGroup(
            withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMenuLayout.createSequentialGroup()
                .addGroup(withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel8))
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnWithdraw2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackFromWithdrawMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawValue, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(withdrawAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        withdrawMenuLayout.setVerticalGroup(
            withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackFromWithdrawMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel8)
                .addGap(48, 48, 48)
                .addGroup(withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(withdrawAccountID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31)
                    .addComponent(withdrawAccountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(withdrawValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnWithdraw2)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jPanel1.add(withdrawMenu, "card4");

        withdrawMenu2.setPreferredSize(new java.awt.Dimension(553, 426));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel27.setText("Dinheiro na mão!");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("Valor sacado:");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Saldo final:");

        withdrawValue2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnCompleteWithdraw.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCompleteWithdraw.setText("Concluir");
        btnCompleteWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteWithdrawActionPerformed(evt);
            }
        });

        finalBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout withdrawMenu2Layout = new javax.swing.GroupLayout(withdrawMenu2);
        withdrawMenu2.setLayout(withdrawMenu2Layout);
        withdrawMenu2Layout.setHorizontalGroup(
            withdrawMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, withdrawMenu2Layout.createSequentialGroup()
                .addContainerGap(142, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addGap(137, 137, 137))
            .addGroup(withdrawMenu2Layout.createSequentialGroup()
                .addGroup(withdrawMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawMenu2Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addGroup(withdrawMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(withdrawMenu2Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(withdrawValue2))
                            .addGroup(withdrawMenu2Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(finalBalance))))
                    .addGroup(withdrawMenu2Layout.createSequentialGroup()
                        .addGap(239, 239, 239)
                        .addComponent(btnCompleteWithdraw)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        withdrawMenu2Layout.setVerticalGroup(
            withdrawMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMenu2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel27)
                .addGap(74, 74, 74)
                .addGroup(withdrawMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(withdrawValue2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(withdrawMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(finalBalance))
                .addGap(39, 39, 39)
                .addComponent(btnCompleteWithdraw)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jPanel1.add(withdrawMenu2, "card10");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Gastar é bom, mas guardar é");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("melhor ainda!");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Quanto você precisa depositar?");

        depositValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        depositValue.setText("jTextField5");

        btnDeposit2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeposit2.setText("Depositar");
        btnDeposit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeposit2ActionPerformed(evt);
            }
        });

        btnBackFromDepositMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBackFromDepositMenu.setText("Voltar");
        btnBackFromDepositMenu.setPreferredSize(new java.awt.Dimension(115, 32));
        btnBackFromDepositMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFromDepositMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositMenuLayout = new javax.swing.GroupLayout(depositMenu);
        depositMenu.setLayout(depositMenuLayout);
        depositMenuLayout.setHorizontalGroup(
            depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDeposit2)
                .addGap(221, 221, 221))
            .addGroup(depositMenuLayout.createSequentialGroup()
                .addGroup(depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackFromDepositMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositMenuLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(depositValue, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(depositMenuLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(depositMenuLayout.createSequentialGroup()
                                .addGap(117, 117, 117)
                                .addComponent(jLabel11))
                            .addComponent(jLabel10))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        depositMenuLayout.setVerticalGroup(
            depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackFromDepositMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(42, 42, 42)
                .addComponent(btnDeposit2)
                .addGap(88, 88, 88))
        );

        jPanel1.add(depositMenu, "card5");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel13.setText("É sempre bom saber se");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel14.setText("tem algo na conta!");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("ID:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Conta:");

        accountBalanceNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountBalanceNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBalanceNumberActionPerformed(evt);
            }
        });

        btnBalance2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBalance2.setText("Ver saldo");
        btnBalance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalance2ActionPerformed(evt);
            }
        });

        accountBalanceId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountBalanceId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Corrente", "2- Poupança" }));

        btnBackFromBalanceMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBackFromBalanceMenu.setText("Voltar");
        btnBackFromBalanceMenu.setPreferredSize(new java.awt.Dimension(115, 32));
        btnBackFromBalanceMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFromBalanceMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout balanceMenuLayout = new javax.swing.GroupLayout(balanceMenu);
        balanceMenu.setLayout(balanceMenuLayout);
        balanceMenuLayout.setHorizontalGroup(
            balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenuLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountBalanceId, 0, 1, Short.MAX_VALUE)
                .addGap(24, 24, 24)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accountBalanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
            .addGroup(balanceMenuLayout.createSequentialGroup()
                .addGroup(balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceMenuLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jLabel14))
                    .addGroup(balanceMenuLayout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel13))
                    .addGroup(balanceMenuLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnBalance2))
                    .addGroup(balanceMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackFromBalanceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        balanceMenuLayout.setVerticalGroup(
            balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackFromBalanceMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(73, 73, 73)
                .addGroup(balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(accountBalanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalanceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnBalance2)
                .addContainerGap(89, Short.MAX_VALUE))
        );

        jPanel1.add(balanceMenu, "card6");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel17.setText("É sempre bom saber se");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel18.setText("tem algo na conta!");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Seu saldo é de:");

        btnCompleteBalanceView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCompleteBalanceView.setText("Concluir");
        btnCompleteBalanceView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteBalanceViewActionPerformed(evt);
            }
        });

        accountBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout balanceMenu2Layout = new javax.swing.GroupLayout(balanceMenu2);
        balanceMenu2.setLayout(balanceMenu2Layout);
        balanceMenu2Layout.setHorizontalGroup(
            balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenu2Layout.createSequentialGroup()
                .addGroup(balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceMenu2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel17))
                    .addGroup(balanceMenu2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel18))
                    .addGroup(balanceMenu2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balanceMenu2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCompleteBalanceView)
                .addGap(221, 221, 221))
        );
        balanceMenu2Layout.setVerticalGroup(
            balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenu2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(78, 78, 78)
                .addGroup(balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(accountBalance))
                .addGap(30, 30, 30)
                .addComponent(btnCompleteBalanceView)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel1.add(balanceMenu2, "card7");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setText("Relembre suas informações");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setText("pessoais aqui!");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("ID:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Conta:");

        accountDataNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnSeeData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeeData.setText("Ver dados");
        btnSeeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeDataActionPerformed(evt);
            }
        });

        accountDataId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountDataId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Corrente", "2- Poupança" }));

        btnBackFromAccountDataMenu.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBackFromAccountDataMenu.setText("Voltar");
        btnBackFromAccountDataMenu.setPreferredSize(new java.awt.Dimension(115, 32));
        btnBackFromAccountDataMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFromAccountDataMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountDataMenuLayout = new javax.swing.GroupLayout(accountDataMenu);
        accountDataMenu.setLayout(accountDataMenuLayout);
        accountDataMenuLayout.setHorizontalGroup(
            accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDataMenuLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(58, 58, 58))
            .addGroup(accountDataMenuLayout.createSequentialGroup()
                .addGroup(accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDataMenuLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel21))
                    .addGroup(accountDataMenuLayout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDataId, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDataNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accountDataMenuLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnSeeData))
                    .addGroup(accountDataMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBackFromAccountDataMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountDataMenuLayout.setVerticalGroup(
            accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDataMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBackFromAccountDataMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(87, 87, 87)
                .addGroup(accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(accountDataNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountDataId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnSeeData)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jPanel1.add(accountDataMenu, "card8");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel24.setText("Estes são seus dados:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Nome:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Telefone:");

        accountDataName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountDataName.setText("jLabel27");

        accountDataPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountDataPhone.setText("JLabel28");

        btnSeeAccountDataCompleted.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeeAccountDataCompleted.setText("Concluir");
        btnSeeAccountDataCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeAccountDataCompletedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountDataMenu2Layout = new javax.swing.GroupLayout(accountDataMenu2);
        accountDataMenu2.setLayout(accountDataMenu2Layout);
        accountDataMenu2Layout.setHorizontalGroup(
            accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDataMenu2Layout.createSequentialGroup()
                .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDataMenu2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel24))
                    .addGroup(accountDataMenu2Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(btnSeeAccountDataCompleted))
                    .addGroup(accountDataMenu2Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel25)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDataName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDataMenu2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDataPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        accountDataMenu2Layout.setVerticalGroup(
            accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDataMenu2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel24)
                .addGap(72, 72, 72)
                .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(accountDataName))
                .addGap(18, 18, 18)
                .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(accountDataPhone))
                .addGap(75, 75, 75)
                .addComponent(btnSeeAccountDataCompleted)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel1.add(accountDataMenu2, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        // TODO add your handling code here:
        startMenu.setVisible(false);
        newAccountMenu.setVisible(true);
    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void btnNewAccount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccount2ActionPerformed
        // TODO add your handling code here:
        Conta.criarConta(nameNewAccount, phoneNewAccount, moneyNewAccount, comboBoxAccountType, newAccountMenu, startMenu, nameNewAccount,
                phoneNewAccount, moneyNewAccount);
    }//GEN-LAST:event_btnNewAccount2ActionPerformed

    private void btnDeposit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeposit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeposit2ActionPerformed

    private void btnBalance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalance2ActionPerformed
        Conta.verSaldo(accountBalanceId, accountBalanceNumber, accountBalance, balanceMenu, balanceMenu2);
    }//GEN-LAST:event_btnBalance2ActionPerformed

    private void btnSeeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeDataActionPerformed
        Conta.verDadosConta(accountDataId, accountDataNumber, accountDataName, accountDataPhone, accountDataMenu, accountDataMenu2);
    }//GEN-LAST:event_btnSeeDataActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        startMenu.setVisible(false);
        balanceMenu.setVisible(true);
        pack();
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void accountBalanceNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBalanceNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountBalanceNumberActionPerformed

    private void btnCompleteBalanceViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteBalanceViewActionPerformed
        balanceMenu2.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnCompleteBalanceViewActionPerformed

    private void btnAccountDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccountDataActionPerformed
        // TODO add your handling code here:
        accountDataMenu.setVisible(true);
        startMenu.setVisible(false);
    }//GEN-LAST:event_btnAccountDataActionPerformed

    private void btnSeeAccountDataCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeAccountDataCompletedActionPerformed
        // TODO add your handling code here:
        accountDataMenu2.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnSeeAccountDataCompletedActionPerformed

    private void btnBackFromNewAccountMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFromNewAccountMenuActionPerformed
        // TODO add your handling code here:
        newAccountMenu.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnBackFromNewAccountMenuActionPerformed

    private void btnBackFromWithdrawMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFromWithdrawMenuActionPerformed
        // TODO add your handling code here:
        withdrawMenu.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnBackFromWithdrawMenuActionPerformed

    private void btnBackFromDepositMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFromDepositMenuActionPerformed
        // TODO add your handling code here:
        depositMenu.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnBackFromDepositMenuActionPerformed

    private void btnBackFromBalanceMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFromBalanceMenuActionPerformed
        // TODO add your handling code here:
        balanceMenu.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnBackFromBalanceMenuActionPerformed

    private void btnBackFromAccountDataMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFromAccountDataMenuActionPerformed
        // TODO add your handling code here:
        accountDataMenu.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnBackFromAccountDataMenuActionPerformed

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdrawActionPerformed
        // TODO add your handling code here:
        withdrawMenu.setVisible(true);
        startMenu.setVisible(false);
    }//GEN-LAST:event_btnWithdrawActionPerformed

    private void btnDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositActionPerformed
        // TODO add your handling code here:
        depositMenu.setVisible(true);
        startMenu.setVisible(false);
    }//GEN-LAST:event_btnDepositActionPerformed

    private void btnWithdraw2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithdraw2ActionPerformed
        // TODO add your handling code here:
        Conta.sacar(withdrawMenu, withdrawMenu2, withdrawAccountID, withdrawAccountNumber, withdrawValue, withdrawValue2, finalBalance);
    }//GEN-LAST:event_btnWithdraw2ActionPerformed

    private void btnCompleteWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteWithdrawActionPerformed
        // TODO add your handling code here:
        withdrawMenu2.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnCompleteWithdrawActionPerformed

    private void withdrawValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_withdrawValueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountBalance;
    private javax.swing.JComboBox<String> accountBalanceId;
    private javax.swing.JTextField accountBalanceNumber;
    private javax.swing.JComboBox<String> accountDataId;
    private javax.swing.JPanel accountDataMenu;
    private javax.swing.JPanel accountDataMenu2;
    private javax.swing.JLabel accountDataName;
    private javax.swing.JTextField accountDataNumber;
    private javax.swing.JLabel accountDataPhone;
    private javax.swing.JPanel balanceMenu;
    private javax.swing.JPanel balanceMenu2;
    private javax.swing.JButton btnAccountData;
    private javax.swing.JButton btnBackFromAccountDataMenu;
    private javax.swing.JButton btnBackFromBalanceMenu;
    private javax.swing.JButton btnBackFromDepositMenu;
    private javax.swing.JButton btnBackFromNewAccountMenu;
    private javax.swing.JButton btnBackFromWithdrawMenu;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnBalance2;
    private javax.swing.JButton btnCompleteBalanceView;
    private javax.swing.JButton btnCompleteWithdraw;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnDeposit2;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnNewAccount2;
    private javax.swing.JButton btnSeeAccountDataCompleted;
    private javax.swing.JButton btnSeeData;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btnWithdraw2;
    private javax.swing.JComboBox<String> comboBoxAccountType;
    private javax.swing.JPanel depositMenu;
    private javax.swing.JTextField depositValue;
    private javax.swing.JLabel finalBalance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField moneyNewAccount;
    private javax.swing.JTextField nameNewAccount;
    private javax.swing.JPanel newAccountMenu;
    private javax.swing.JTextField phoneNewAccount;
    private javax.swing.JPanel startMenu;
    private javax.swing.JComboBox<String> withdrawAccountID;
    private javax.swing.JTextField withdrawAccountNumber;
    private javax.swing.JPanel withdrawMenu;
    private javax.swing.JPanel withdrawMenu2;
    private javax.swing.JTextField withdrawValue;
    private javax.swing.JLabel withdrawValue2;
    // End of variables declaration//GEN-END:variables
}