/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.bancojava;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Arthu
 */
public class MainFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainFrame.class.getName());

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        startMenu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnNewAccount = new javax.swing.JButton();
        btnBalance = new javax.swing.JButton();
        btnAccountData = new javax.swing.JButton();
        btnWithdraw = new javax.swing.JButton();
        btnDeposit = new javax.swing.JButton();
        newAccountMenu = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nameNewAccount = new javax.swing.JTextField();
        phoneNewAccount = new javax.swing.JTextField();
        moneyNewAccount = new javax.swing.JTextField();
        btnNewAccount2 = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        comboBoxAccountType = new javax.swing.JComboBox<>();
        withdrawMenu = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        withdrawValue = new javax.swing.JTextField();
        btnWithdraw2 = new javax.swing.JButton();
        depositMenu = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        depositValue = new javax.swing.JTextField();
        btnDeposit2 = new javax.swing.JButton();
        balanceMenu = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        accountBalanceNumber = new javax.swing.JTextField();
        btnBalance2 = new javax.swing.JButton();
        accountBalanceId = new javax.swing.JComboBox<>();
        balanceMenu2 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        btnCompleteBalanceView = new javax.swing.JButton();
        accountBalance = new javax.swing.JLabel();
        accountDataMenu = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        AccountDataId = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        accountDataNumber = new javax.swing.JTextField();
        btnSeeData = new javax.swing.JButton();
        accountDataMenu2 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setText("Banco do Arthur");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setText("Seu dinheiro, sua vida!");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu Iniciar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        btnNewAccount.setText("Criar conta");
        btnNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccountActionPerformed(evt);
            }
        });

        btnBalance.setText("Ver saldo");
        btnBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalanceActionPerformed(evt);
            }
        });

        btnAccountData.setText("Dados da conta");

        btnWithdraw.setText("Sacar");

        btnDeposit.setText("Depositar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBalance, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnAccountData, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(btnWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNewAccount)
                    .addComponent(btnBalance)
                    .addComponent(btnAccountData))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw)
                    .addComponent(btnDeposit))
                .addContainerGap(120, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout startMenuLayout = new javax.swing.GroupLayout(startMenu);
        startMenu.setLayout(startMenuLayout);
        startMenuLayout.setHorizontalGroup(
            startMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startMenuLayout.createSequentialGroup()
                .addGroup(startMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(startMenuLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(jLabel1)
                        .addGap(0, 133, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(86, 86, 86))
        );
        startMenuLayout.setVerticalGroup(
            startMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(startMenu, "card2");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setText("Hora de ter uma conta");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setText("com a gente!");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Nome:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Telefone:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Valor inicial:");

        nameNewAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        phoneNewAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        phoneNewAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneNewAccountActionPerformed(evt);
            }
        });

        moneyNewAccount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        btnNewAccount2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNewAccount2.setText("Criar conta");
        btnNewAccount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewAccount2ActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("Tipo de conta:");

        comboBoxAccountType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        comboBoxAccountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1- Corrente", "2- Poupança" }));

        javax.swing.GroupLayout newAccountMenuLayout = new javax.swing.GroupLayout(newAccountMenu);
        newAccountMenu.setLayout(newAccountMenuLayout);
        newAccountMenuLayout.setHorizontalGroup(
            newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnNewAccount2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountMenuLayout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(139, 139, 139))
            .addGroup(newAccountMenuLayout.createSequentialGroup()
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(newAccountMenuLayout.createSequentialGroup()
                                .addGap(72, 72, 72)
                                .addComponent(jLabel4))))
                    .addGroup(newAccountMenuLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(newAccountMenuLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(newAccountMenuLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(phoneNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(moneyNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        newAccountMenuLayout.setVerticalGroup(
            newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newAccountMenuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nameNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(phoneNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(moneyNewAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newAccountMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(comboBoxAccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnNewAccount2)
                .addGap(51, 51, 51))
        );

        jPanel1.add(newAccountMenu, "card3");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel8.setText("Precisando de uma grana, né!");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Quanto você precisa?");

        withdrawValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        withdrawValue.setText("jTextField4");

        btnWithdraw2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnWithdraw2.setText("Sacar");

        javax.swing.GroupLayout withdrawMenuLayout = new javax.swing.GroupLayout(withdrawMenu);
        withdrawMenu.setLayout(withdrawMenuLayout);
        withdrawMenuLayout.setHorizontalGroup(
            withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMenuLayout.createSequentialGroup()
                .addGroup(withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel8))
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(withdrawValue, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(withdrawMenuLayout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(btnWithdraw2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        withdrawMenuLayout.setVerticalGroup(
            withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(withdrawMenuLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel8)
                .addGap(94, 94, 94)
                .addGroup(withdrawMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(withdrawValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(btnWithdraw2)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jPanel1.add(withdrawMenu, "card4");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel10.setText("Gastar é bom. Mas guardar é");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel11.setText("melhor ainda!");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setText("Quanto você precisa depositar?");

        depositValue.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        depositValue.setText("jTextField5");

        btnDeposit2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnDeposit2.setText("Depositar");
        btnDeposit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeposit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout depositMenuLayout = new javax.swing.GroupLayout(depositMenu);
        depositMenu.setLayout(depositMenuLayout);
        depositMenuLayout.setHorizontalGroup(
            depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositMenuLayout.createSequentialGroup()
                .addGroup(depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(depositMenuLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel11))
                    .addGroup(depositMenuLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(depositMenuLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(depositValue, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel10))))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, depositMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDeposit2)
                .addGap(221, 221, 221))
        );
        depositMenuLayout.setVerticalGroup(
            depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(depositMenuLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(depositMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(depositValue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(42, 42, 42)
                .addComponent(btnDeposit2)
                .addGap(88, 88, 88))
        );

        jPanel1.add(depositMenu, "card5");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel13.setText("É sempre bom saber se");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel14.setText("tem algo na conta!");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("ID:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("Conta:");

        accountBalanceNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountBalanceNumber.setText("jTextField7");
        accountBalanceNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountBalanceNumberActionPerformed(evt);
            }
        });

        btnBalance2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnBalance2.setText("Ver saldo");
        btnBalance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBalance2ActionPerformed(evt);
            }
        });

        accountBalanceId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountBalanceId.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2" }));

        javax.swing.GroupLayout balanceMenuLayout = new javax.swing.GroupLayout(balanceMenu);
        balanceMenu.setLayout(balanceMenuLayout);
        balanceMenuLayout.setHorizontalGroup(
            balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenuLayout.createSequentialGroup()
                .addGroup(balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(balanceMenuLayout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(jLabel13))
                            .addGroup(balanceMenuLayout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel14)))
                        .addGroup(balanceMenuLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel15)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accountBalanceId, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(accountBalanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(23, 23, 23)))
                    .addGroup(balanceMenuLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnBalance2)))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        balanceMenuLayout.setVerticalGroup(
            balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(73, 73, 73)
                .addGroup(balanceMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(accountBalanceNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountBalanceId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnBalance2)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jPanel1.add(balanceMenu, "card6");

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel17.setText("É sempre bom saber se");

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel18.setText("tem algo na conta!");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("Seu saldo é de:");

        btnCompleteBalanceView.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnCompleteBalanceView.setText("Concluir");
        btnCompleteBalanceView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompleteBalanceViewActionPerformed(evt);
            }
        });

        accountBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountBalance.setText("jLabel20fdsafad");

        javax.swing.GroupLayout balanceMenu2Layout = new javax.swing.GroupLayout(balanceMenu2);
        balanceMenu2.setLayout(balanceMenu2Layout);
        balanceMenu2Layout.setHorizontalGroup(
            balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenu2Layout.createSequentialGroup()
                .addGroup(balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(balanceMenu2Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel17))
                    .addGroup(balanceMenu2Layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel18))
                    .addGroup(balanceMenu2Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, balanceMenu2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCompleteBalanceView)
                .addGap(221, 221, 221))
        );
        balanceMenu2Layout.setVerticalGroup(
            balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(balanceMenu2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addGap(78, 78, 78)
                .addGroup(balanceMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(accountBalance))
                .addGap(30, 30, 30)
                .addComponent(btnCompleteBalanceView)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jPanel1.add(balanceMenu2, "card7");

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel20.setText("Relembre suas informações");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel21.setText("pessoais aqui!");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("Id:");

        AccountDataId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        AccountDataId.setText("jTextField1");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("Conta:");

        accountDataNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        accountDataNumber.setText("jTextField2");

        btnSeeData.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSeeData.setText("Ver dados");
        btnSeeData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeeDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout accountDataMenuLayout = new javax.swing.GroupLayout(accountDataMenu);
        accountDataMenu.setLayout(accountDataMenuLayout);
        accountDataMenuLayout.setHorizontalGroup(
            accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accountDataMenuLayout.createSequentialGroup()
                .addGap(0, 59, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(58, 58, 58))
            .addGroup(accountDataMenuLayout.createSequentialGroup()
                .addGroup(accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDataMenuLayout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jLabel21))
                    .addGroup(accountDataMenuLayout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jLabel22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AccountDataId, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(accountDataNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(accountDataMenuLayout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addComponent(btnSeeData)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accountDataMenuLayout.setVerticalGroup(
            accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDataMenuLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(87, 87, 87)
                .addGroup(accountDataMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AccountDataId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23)
                    .addComponent(accountDataNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(btnSeeData)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jPanel1.add(accountDataMenu, "card8");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel24.setText("Este são seus dados:");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("Nome:");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("Telefone:");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("jLabel27");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("JLabel28");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("Conta:");

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("jLabel30");

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("Saldo:");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setText("jLabel32");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Concluir");

        javax.swing.GroupLayout accountDataMenu2Layout = new javax.swing.GroupLayout(accountDataMenu2);
        accountDataMenu2.setLayout(accountDataMenu2Layout);
        accountDataMenu2Layout.setHorizontalGroup(
            accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDataMenu2Layout.createSequentialGroup()
                .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(accountDataMenu2Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(jLabel24))
                    .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(accountDataMenu2Layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(accountDataMenu2Layout.createSequentialGroup()
                                    .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel29)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(accountDataMenu2Layout.createSequentialGroup()
                                    .addGap(35, 35, 35)
                                    .addComponent(jLabel31)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, accountDataMenu2Layout.createSequentialGroup()
                            .addGap(88, 88, 88)
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(accountDataMenu2Layout.createSequentialGroup()
                        .addGap(219, 219, 219)
                        .addComponent(jButton1)))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        accountDataMenu2Layout.setVerticalGroup(
            accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accountDataMenu2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel24)
                .addGap(72, 72, 72)
                .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(jLabel27))
                .addGap(18, 18, 18)
                .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addGap(18, 18, 18)
                .addGroup(accountDataMenu2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel32))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        jPanel1.add(accountDataMenu2, "card9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccountActionPerformed
        // TODO add your handling code here:
        startMenu.setVisible(false);
        newAccountMenu.setVisible(true);
        pack();
    }//GEN-LAST:event_btnNewAccountActionPerformed

    private void btnNewAccount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewAccount2ActionPerformed
        // TODO add your handling code here:
        Conta.criarConta(nameNewAccount, phoneNewAccount, moneyNewAccount, comboBoxAccountType);
        newAccountMenu.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnNewAccount2ActionPerformed

    private void btnDeposit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeposit2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeposit2ActionPerformed

    private void btnBalance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalance2ActionPerformed
        Conta.verSaldo(accountBalanceId, accountBalanceNumber, accountBalance);
        balanceMenu.setVisible(false);
        balanceMenu2.setVisible(true);
    }//GEN-LAST:event_btnBalance2ActionPerformed

    private void btnSeeDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeeDataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSeeDataActionPerformed

    private void phoneNewAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneNewAccountActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneNewAccountActionPerformed

    private void btnBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBalanceActionPerformed
        startMenu.setVisible(false);
        balanceMenu.setVisible(true);
        pack();
    }//GEN-LAST:event_btnBalanceActionPerformed

    private void accountBalanceNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountBalanceNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountBalanceNumberActionPerformed

    private void btnCompleteBalanceViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompleteBalanceViewActionPerformed
        balanceMenu2.setVisible(false);
        startMenu.setVisible(true);
    }//GEN-LAST:event_btnCompleteBalanceViewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainFrame().setVisible(true));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AccountDataId;
    private javax.swing.JLabel accountBalance;
    private javax.swing.JComboBox<String> accountBalanceId;
    private javax.swing.JTextField accountBalanceNumber;
    private javax.swing.JPanel accountDataMenu;
    private javax.swing.JPanel accountDataMenu2;
    private javax.swing.JTextField accountDataNumber;
    private javax.swing.JPanel balanceMenu;
    private javax.swing.JPanel balanceMenu2;
    private javax.swing.JButton btnAccountData;
    private javax.swing.JButton btnBalance;
    private javax.swing.JButton btnBalance2;
    private javax.swing.JButton btnCompleteBalanceView;
    private javax.swing.JButton btnDeposit;
    private javax.swing.JButton btnDeposit2;
    private javax.swing.JButton btnNewAccount;
    private javax.swing.JButton btnNewAccount2;
    private javax.swing.JButton btnSeeData;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JButton btnWithdraw2;
    private javax.swing.JComboBox<String> comboBoxAccountType;
    private javax.swing.JPanel depositMenu;
    private javax.swing.JTextField depositValue;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField moneyNewAccount;
    private javax.swing.JTextField nameNewAccount;
    private javax.swing.JPanel newAccountMenu;
    private javax.swing.JTextField phoneNewAccount;
    private javax.swing.JPanel startMenu;
    private javax.swing.JPanel withdrawMenu;
    private javax.swing.JTextField withdrawValue;
    // End of variables declaration//GEN-END:variables
}
